# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.CharField(max_length=100, verbose_name='Quantidade')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('descri', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem_perfil', models.ImageField(blank=True, default='imagens/perfil/noperfil.png', null=True, upload_to='imagens/perfil', verbose_name='Imagem')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('complemento', models.CharField(max_length=200, verbose_name='Complemento')),
                ('usuario', models.CharField(max_length=300, verbose_name='Usuario')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipo_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Produto'),
        ),
        migrations.AddField(
            model_name='compra_produtos',
            name='produtos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produtos'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
